# Generated by Django 5.1.1 on 2024-09-27 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "code",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Measure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("short_name", models.CharField(max_length=255, null=True)),
                ("slug", models.SlugField(null=True, unique=True)),
                ("description", models.TextField()),
                ("sql_file", models.CharField(max_length=255)),
                ("category", models.CharField(max_length=255, null=True)),
                ("why", models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="VTM",
            fields=[
                (
                    "vtm",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Organisation",
            fields=[
                (
                    "ods_code",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("ods_name", models.CharField(max_length=255)),
                ("region", models.CharField(max_length=100)),
                (
                    "successor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="predecessors",
                        to="viewer.organisation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrgSubmissionCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.DateField()),
                ("has_submitted", models.BooleanField()),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="viewer.organisation",
                    ),
                ),
                (
                    "successor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="successors",
                        to="viewer.organisation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PrecomputedMeasure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.DateField()),
                ("quantity", models.FloatField(null=True)),
                (
                    "measure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="precomputed_measures",
                        to="viewer.measure",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="precomputed_measures",
                        to="viewer.organisation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VMP",
            fields=[
                (
                    "code",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "ingredients",
                    models.ManyToManyField(
                        null=True, related_name="vmps", to="viewer.ingredient"
                    ),
                ),
                (
                    "vtm",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vmps",
                        to="viewer.vtm",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IngredientQuantity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year_month", models.DateField()),
                ("quantity", models.FloatField(null=True)),
                ("unit", models.CharField(max_length=50, null=True)),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingredient_quantities",
                        to="viewer.ingredient",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingredient_quantities",
                        to="viewer.organisation",
                    ),
                ),
                (
                    "vmp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingredient_quantities",
                        to="viewer.vmp",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "year_month",
                    "ingredient__name",
                    "vmp__name",
                    "organisation__ods_name",
                ],
            },
        ),
        migrations.CreateModel(
            name="Dose",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year_month", models.DateField()),
                ("quantity", models.FloatField(null=True)),
                ("unit", models.CharField(max_length=50)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doses",
                        to="viewer.organisation",
                    ),
                ),
                (
                    "vmp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="doses",
                        to="viewer.vmp",
                    ),
                ),
            ],
            options={
                "ordering": ["year_month", "vmp__name", "organisation__ods_name"],
            },
        ),
        migrations.AddIndex(
            model_name="organisation",
            index=models.Index(
                fields=["ods_name"], name="viewer_orga_ods_nam_e7cb65_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="orgsubmissioncache",
            unique_together={("organisation", "month")},
        ),
        migrations.AddIndex(
            model_name="precomputedmeasure",
            index=models.Index(
                fields=["measure", "organisation", "month"],
                name="viewer_prec_measure_81a373_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="precomputedmeasure",
            unique_together={("measure", "organisation", "month")},
        ),
        migrations.AddIndex(
            model_name="ingredientquantity",
            index=models.Index(fields=["vmp"], name="viewer_ingr_vmp_id_71be0e_idx"),
        ),
        migrations.AddIndex(
            model_name="ingredientquantity",
            index=models.Index(
                fields=["organisation"], name="viewer_ingr_organis_4645a4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ingredientquantity",
            index=models.Index(
                fields=["ingredient"], name="viewer_ingr_ingredi_e60421_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ingredientquantity",
            index=models.Index(
                fields=["year_month"], name="viewer_ingr_year_mo_3f376f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dose",
            index=models.Index(fields=["vmp"], name="viewer_dose_vmp_id_70abef_idx"),
        ),
        migrations.AddIndex(
            model_name="dose",
            index=models.Index(
                fields=["organisation"], name="viewer_dose_organis_c8a982_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="dose",
            index=models.Index(
                fields=["year_month"], name="viewer_dose_year_mo_1bb51b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vmp",
            index=models.Index(fields=["name"], name="viewer_vmp_name_4d3229_idx"),
        ),
    ]
