# Generated by Django 5.1 on 2024-08-30 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_month', models.DateField()),
                ('vmp_code', models.CharField(max_length=20)),
                ('vmp_name', models.CharField(max_length=255)),
                ('ods_code', models.CharField(max_length=10)),
                ('ods_name', models.CharField(max_length=255)),
                ('SCMD_quantity', models.FloatField()),
                ('SCMD_quantity_basis', models.CharField(max_length=50)),
                ('dose_quantity', models.FloatField()),
                ('converted_udfs', models.FloatField()),
                ('udfs_basis', models.CharField(max_length=50)),
                ('dose_unit', models.CharField(max_length=50)),
                ('df_ind', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['year_month', 'vmp_name', 'ods_name'],
            },
        ),
    ]
