# Generated by Django 5.1.1 on 2024-10-02 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("viewer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="icb",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
