# Generated by Django 4.2.17 on 2024-12-11 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("viewer", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vmp",
            name="ingredients",
            field=models.ManyToManyField(related_name="vmps", to="viewer.ingredient"),
        ),
        migrations.AlterField(
            model_name="vmp",
            name="ont_form_routes",
            field=models.ManyToManyField(related_name="vmps", to="viewer.ontformroute"),
        ),
        migrations.AlterField(
            model_name="vmp",
            name="routes",
            field=models.ManyToManyField(related_name="vmps", to="viewer.route"),
        ),
    ]
