# Generated by Django 5.1 on 2024-08-30 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0002_organisation_dose_organisation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dose',
            options={'ordering': ['year_month', 'vmp_name', 'organisation__ods_name']},
        ),
        migrations.RemoveField(
            model_name='dose',
            name='ods_code',
        ),
        migrations.RemoveField(
            model_name='dose',
            name='ods_name',
        ),
        migrations.AlterField(
            model_name='dose',
            name='organisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doses', to='viewer.organisation'),
        ),
    ]
