# Generated by Django 4.2.17 on 2024-12-16 15:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("viewer", "0002_alter_vmp_ingredients_alter_vmp_ont_form_routes_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ATC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=7,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Invalid ATC code",
                                regex="^[A-Z][0-9]{2}[A-Z][0-9]{2}[A-Z][0-9]{2}$",
                            )
                        ],
                    ),
                ),
                ("name", models.CharField(max_length=255, null=True)),
                ("level", models.IntegerField(null=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="viewer.atc",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["code"], name="viewer_atc_code_918ea6_idx")
                ],
            },
        ),
    ]
