# Generated by Django 5.1.1 on 2024-10-03 10:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("viewer", "0002_organisation_icb"),
    ]

    operations = [
        migrations.CreateModel(
            name="ATC",
            fields=[
                (
                    "code",
                    models.CharField(
                        max_length=7,
                        primary_key=True,
                        serialize=False,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Invalid ATC code format",
                                regex="^[A-Z](\\d{2}([A-Z](\\d{2}([A-Z](\\d{2})?)?)?)?)?$",
                            )
                        ],
                    ),
                ),
                ("bnf_code", models.CharField(max_length=20, null=True)),
                ("name", models.CharField(max_length=255)),
                ("level", models.IntegerField()),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="viewer.atc",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="vmp",
            name="atcs",
            field=models.ManyToManyField(
                null=True, related_name="vmps", to="viewer.atc"
            ),
        ),
        migrations.AddIndex(
            model_name="atc",
            index=models.Index(fields=["code"], name="viewer_atc_code_918ea6_idx"),
        ),
        migrations.AddIndex(
            model_name="atc",
            index=models.Index(fields=["level"], name="viewer_atc_level_ca9026_idx"),
        ),
        migrations.AddIndex(
            model_name="atc",
            index=models.Index(fields=["parent"], name="viewer_atc_parent__3e9d54_idx"),
        ),
    ]
