# Generated by Django 5.1.1 on 2024-10-08 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("viewer", "0003_atc_vmp_atcs_atc_viewer_atc_code_918ea6_idx_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="measure",
            old_name="why",
            new_name="reason",
        ),
        migrations.RenameField(
            model_name="measure",
            old_name="description",
            new_name="why_it_matters",
        ),
    ]
