# Generated by Django 5.1 on 2024-08-30 11:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0003_alter_dose_options_remove_dose_ods_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='VTM',
            fields=[
                ('vtm', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name='dose',
            options={'ordering': ['year_month', 'vmp__name', 'organisation__ods_name']},
        ),
        migrations.RenameField(
            model_name='dose',
            old_name='dose_quantity',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='dose',
            old_name='dose_unit',
            new_name='unit',
        ),
        migrations.RemoveField(
            model_name='dose',
            name='SCMD_quantity',
        ),
        migrations.RemoveField(
            model_name='dose',
            name='SCMD_quantity_basis',
        ),
        migrations.RemoveField(
            model_name='dose',
            name='converted_udfs',
        ),
        migrations.RemoveField(
            model_name='dose',
            name='df_ind',
        ),
        migrations.RemoveField(
            model_name='dose',
            name='udfs_basis',
        ),
        migrations.RemoveField(
            model_name='dose',
            name='vmp_code',
        ),
        migrations.RemoveField(
            model_name='dose',
            name='vmp_name',
        ),
        migrations.RemoveField(
            model_name='organisation',
            name='id',
        ),
        migrations.AlterField(
            model_name='organisation',
            name='ods_code',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='VMP',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('ingredients', models.ManyToManyField(related_name='vmps', to='viewer.ingredient')),
                ('vtm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vmps', to='viewer.vtm')),
            ],
        ),
        migrations.CreateModel(
            name='SCMD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_month', models.DateField()),
                ('quantity', models.FloatField()),
                ('unit', models.CharField(max_length=50)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scmds', to='viewer.organisation')),
                ('vmp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scmds', to='viewer.vmp')),
            ],
            options={
                'ordering': ['year_month', 'vmp__name', 'organisation__ods_name'],
            },
        ),
        migrations.CreateModel(
            name='IngredientQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_month', models.DateField()),
                ('quantity', models.FloatField()),
                ('unit', models.CharField(max_length=50)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_quantities', to='viewer.ingredient')),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_quantities', to='viewer.organisation')),
                ('vmp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_quantities', to='viewer.vmp')),
            ],
            options={
                'ordering': ['year_month', 'ingredient__name', 'vmp__name', 'organisation__ods_name'],
            },
        ),
        migrations.AddField(
            model_name='dose',
            name='vmp',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='doses', to='viewer.vmp'),
            preserve_default=False,
        ),
    ]
