# Generated by Django 4.2.17 on 2024-12-16 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("viewer", "0003_atc"),
    ]

    operations = [
        migrations.AddField(
            model_name="vmp",
            name="atcs",
            field=models.ManyToManyField(related_name="vmps", to="viewer.atc"),
        ),
    ]
