# Generated by Django 5.1.1 on 2024-10-08 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("viewer", "0004_rename_why_measure_reason_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="measure",
            name="draft",
            field=models.BooleanField(default=True),
        ),
    ]
