# Generated by Django 5.1 on 2024-08-30 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0004_ingredient_vtm_alter_dose_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vmp',
            name='ingredients',
            field=models.ManyToManyField(null=True, related_name='vmps', to='viewer.ingredient'),
        ),
        migrations.AlterField(
            model_name='vmp',
            name='vtm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vmps', to='viewer.vtm'),
        ),
    ]
