# Generated by Django 5.1 on 2024-08-30 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0005_alter_vmp_ingredients_alter_vmp_vtm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dose',
            name='quantity',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='scmd',
            name='quantity',
            field=models.FloatField(null=True),
        ),
    ]
