# Generated by Django 4.2.17 on 2024-12-16 16:53

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("viewer", "0005_ddd"),
    ]

    operations = [
        migrations.CreateModel(
            name="DDDQuantity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=django.contrib.postgres.fields.ArrayField(
                            base_field=models.CharField(max_length=255, null=True),
                            size=3,
                        ),
                        help_text="Array of [year_month, quantity, unit] entries",
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ddd_quantities",
                        to="viewer.organisation",
                    ),
                ),
                (
                    "vmp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ddd_quantities",
                        to="viewer.vmp",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["vmp", "organisation"],
                        name="viewer_dddq_vmp_id_e06c35_idx",
                    )
                ],
                "unique_together": {("vmp", "organisation")},
            },
        ),
    ]
