# Generated by Django 5.1.1 on 2024-10-08 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("viewer", "0005_measure_draft"),
    ]

    operations = [
        migrations.CreateModel(
            name="MeasureReason",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason", models.CharField(max_length=255)),
                ("colour", models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name="measure",
            name="reason",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="measures",
                to="viewer.measurereason",
            ),
        ),
    ]
