# Generated by Django 5.1 on 2024-08-31 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0006_alter_dose_quantity_alter_scmd_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientquantity',
            name='quantity',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ingredientquantity',
            name='unit',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
