# Generated by Django 4.2.17 on 2024-12-16 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("viewer", "0006_dddquantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="measure",
            name="quantity_type",
            field=models.CharField(
                choices=[
                    ("dose", "Dose"),
                    ("ingredient", "Ingredient Quantity"),
                    ("ddd", "DDD"),
                ],
                default="dose",
                max_length=20,
            ),
        ),
    ]
