# Generated by Django 5.1.1 on 2024-10-08 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("viewer", "0006_measurereason_alter_measure_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="measurereason",
            name="description",
            field=models.TextField(null=True),
        ),
    ]
