# Generated by Django 4.2.17 on 2025-02-18 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("viewer", "0007_alter_measure_quantity_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="measure",
            name="authored_by",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="measure",
            name="checked_by",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="measure",
            name="date_reviewed",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="measure",
            name="next_review",
            field=models.DateField(null=True),
        ),
    ]
