# Generated by Django 5.1.1 on 2024-10-10 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("viewer", "0007_measurereason_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="measure",
            name="category",
        ),
    ]
