# Generated by Django 5.1.1 on 2024-10-15 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("viewer", "0008_remove_measure_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrecomputedMeasureAggregated",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=255, null=True)),
                ("month", models.DateField()),
                ("quantity", models.FloatField(null=True)),
                (
                    "category",
                    models.CharField(
                        choices=[("region", "Region"), ("icb", "ICB")], max_length=20
                    ),
                ),
                (
                    "measure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="precomputed_measures_aggregated",
                        to="viewer.measure",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["measure", "category", "label", "month"],
                        name="viewer_prec_measure_97a1da_idx",
                    )
                ],
                "unique_together": {("measure", "category", "label", "month")},
            },
        ),
        migrations.CreateModel(
            name="PrecomputedPercentile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.DateField()),
                ("percentile", models.IntegerField()),
                ("quantity", models.FloatField(null=True)),
                (
                    "measure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="precomputed_percentiles",
                        to="viewer.measure",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["measure", "month", "percentile"],
                        name="viewer_prec_measure_ef2864_idx",
                    )
                ],
                "unique_together": {("measure", "month", "percentile")},
            },
        ),
    ]
