# Generated by Django 4.2.17 on 2025-02-18 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("viewer", "0009_remove_measure_sql_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="measure",
            name="slug",
            field=models.SlugField(unique=True),
        ),
    ]
