# Generated by Django 5.1.1 on 2024-10-17 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("viewer", "0009_precomputedmeasureaggregated_precomputedpercentile"),
    ]

    operations = [
        migrations.AddField(
            model_name="vmp",
            name="form",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
