# Generated by Django 5.1.1 on 2024-09-05 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0009_organisation_successor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientquantity',
            options={},
        ),
        migrations.AddIndex(
            model_name='dose',
            index=models.Index(fields=['vmp'], name='viewer_dose_vmp_id_70abef_idx'),
        ),
    ]
