# Generated by Django 4.2.17 on 2025-02-18 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("viewer", "0010_alter_measure_slug"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="MeasureReason",
            new_name="MeasureTag",
        ),
        migrations.RenameField(
            model_name="measuretag",
            old_name="reason",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="measure",
            name="reason",
        ),
        migrations.AddField(
            model_name="measure",
            name="tags",
            field=models.ManyToManyField(
                related_name="measures", to="viewer.measuretag"
            ),
        ),
    ]
