# Generated by Django 5.1.1 on 2024-10-17 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("viewer", "0010_vmp_form"),
    ]

    operations = [
        migrations.CreateModel(
            name="OntFormRoute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name="vmp",
            name="ont_form_routes",
            field=models.ManyToManyField(
                null=True, related_name="vmps", to="viewer.ontformroute"
            ),
        ),
    ]
