# Generated by Django 5.1.1 on 2024-09-05 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0010_alter_ingredientquantity_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredientquantity',
            options={'ordering': ['year_month', 'ingredient__name', 'vmp__name', 'organisation__ods_name']},
        ),
        migrations.AddIndex(
            model_name='ingredientquantity',
            index=models.Index(fields=['vmp'], name='viewer_ingr_vmp_id_71be0e_idx'),
        ),
    ]
