# Generated by Django 5.1 on 2025-02-26 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0011_rename_measurereason_measuretag_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Content Cache',
                'verbose_name_plural': 'Content Cache',
                'managed': False,
            },
        ),
    ]
