# Generated by Django 5.1.1 on 2024-10-17 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("viewer", "0011_ontformroute_vmp_ont_form_routes"),
    ]

    operations = [
        migrations.AddField(
            model_name="measure",
            name="denominator_vmps",
            field=models.ManyToManyField(
                related_name="measures_denominator", to="viewer.vmp"
            ),
        ),
        migrations.AddField(
            model_name="measure",
            name="numerator_vmps",
            field=models.ManyToManyField(
                related_name="measures_numerator", to="viewer.vmp"
            ),
        ),
    ]
