# Generated by Django 5.1.1 on 2024-09-05 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0011_alter_ingredientquantity_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='dose',
            name='viewer_dose_vmp_id_70abef_idx',
        ),
        migrations.RemoveIndex(
            model_name='ingredientquantity',
            name='viewer_ingr_vmp_id_71be0e_idx',
        ),
        migrations.AddIndex(
            model_name='dose',
            index=models.Index(fields=['vmp', 'organisation'], name='viewer_dose_vmp_id_2a807b_idx'),
        ),
        migrations.AddIndex(
            model_name='dose',
            index=models.Index(fields=['year_month'], name='viewer_dose_year_mo_1bb51b_idx'),
        ),
        migrations.AddIndex(
            model_name='ingredientquantity',
            index=models.Index(fields=['vmp', 'organisation', 'ingredient'], name='viewer_ingr_vmp_id_0bfa89_idx'),
        ),
        migrations.AddIndex(
            model_name='ingredientquantity',
            index=models.Index(fields=['year_month'], name='viewer_ingr_year_mo_3f376f_idx'),
        ),
        migrations.AddIndex(
            model_name='organisation',
            index=models.Index(fields=['ods_name'], name='viewer_orga_ods_nam_e7cb65_idx'),
        ),
        migrations.AddIndex(
            model_name='scmd',
            index=models.Index(fields=['vmp', 'organisation'], name='viewer_scmd_vmp_id_34963d_idx'),
        ),
        migrations.AddIndex(
            model_name='scmd',
            index=models.Index(fields=['year_month'], name='viewer_scmd_year_mo_32a391_idx'),
        ),
        migrations.AddIndex(
            model_name='vmp',
            index=models.Index(fields=['name'], name='viewer_vmp_name_4d3229_idx'),
        ),
    ]
