# Generated by Django 5.1 on 2025-04-04 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("viewer", "0012_contentcache"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vmp",
            name="form",
        ),
        migrations.RemoveField(
            model_name="vmp",
            name="routes",
        ),
        migrations.AlterField(
            model_name="datastatus",
            name="year_month",
            field=models.DateField(unique=True),
        ),
    ]
