# Generated by Django 5.1.1 on 2024-10-17 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("viewer", "0012_measure_denominator_vmps_measure_numerator_vmps"),
    ]

    operations = [
        migrations.AddField(
            model_name="measure",
            name="description",
            field=models.TextField(null=True),
        ),
    ]
