# Generated by Django 5.1 on 2024-09-09 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("viewer", "0012_remove_dose_viewer_dose_vmp_id_70abef_idx_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="dose",
            name="viewer_dose_vmp_id_2a807b_idx",
        ),
        migrations.RemoveIndex(
            model_name="ingredientquantity",
            name="viewer_ingr_vmp_id_0bfa89_idx",
        ),
        migrations.RemoveIndex(
            model_name="scmd",
            name="viewer_scmd_vmp_id_34963d_idx",
        ),
        migrations.AddIndex(
            model_name="dose",
            index=models.Index(fields=["vmp"], name="viewer_dose_vmp_id_70abef_idx"),
        ),
        migrations.AddIndex(
            model_name="dose",
            index=models.Index(
                fields=["organisation"], name="viewer_dose_organis_c8a982_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ingredientquantity",
            index=models.Index(fields=["vmp"], name="viewer_ingr_vmp_id_71be0e_idx"),
        ),
        migrations.AddIndex(
            model_name="ingredientquantity",
            index=models.Index(
                fields=["organisation"], name="viewer_ingr_organis_4645a4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ingredientquantity",
            index=models.Index(
                fields=["ingredient"], name="viewer_ingr_ingredi_e60421_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scmd",
            index=models.Index(fields=["vmp"], name="viewer_scmd_vmp_id_d6d6b1_idx"),
        ),
        migrations.AddIndex(
            model_name="scmd",
            index=models.Index(
                fields=["organisation"], name="viewer_scmd_organis_a5ab28_idx"
            ),
        ),
    ]
