# Generated by Django 5.1 on 2025-04-04 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("viewer", "0013_remove_vmp_form_remove_vmp_routes_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Route",
            new_name="WHORoute",
        ),
        migrations.RemoveIndex(
            model_name="ddd",
            name="viewer_ddd_vmp_id_13d2b4_idx",
        ),
        migrations.RenameField(
            model_name="ddd",
            old_name="route",
            new_name="who_route",
        ),
        migrations.RenameIndex(
            model_name="whoroute",
            new_name="viewer_whor_code_f41fdc_idx",
            old_name="viewer_rout_code_e7cb68_idx",
        ),
        migrations.AddField(
            model_name="ontformroute",
            name="who_route",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ont_form_routes",
                to="viewer.whoroute",
            ),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="ddd",
            index=models.Index(
                fields=["vmp", "who_route"], name="viewer_ddd_vmp_id_f56b00_idx"
            ),
        ),
    ]
