# Generated by Django 5.1.1 on 2024-09-24 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("viewer", "0013_remove_dose_viewer_dose_vmp_id_2a807b_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="measure",
            name="category",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="measure",
            name="why",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name="SCMD",
        ),
    ]
