# Generated by Django 5.1.1 on 2024-10-17 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("viewer", "0013_measure_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="precomputedmeasure",
            name="denominator",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="precomputedmeasure",
            name="numerator",
            field=models.FloatField(null=True),
        ),
    ]
