# Generated by Django 5.1.1 on 2024-10-17 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("viewer", "0014_precomputedmeasure_denominator_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="precomputedmeasureaggregated",
            name="denominator",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="precomputedmeasureaggregated",
            name="numerator",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="precomputedmeasureaggregated",
            name="category",
            field=models.CharField(
                choices=[
                    ("region", "Region"),
                    ("icb", "ICB"),
                    ("national", "National"),
                ],
                max_length=20,
            ),
        ),
    ]
