# Generated by Django 5.1.1 on 2024-09-24 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("viewer", "0014_measure_category_measure_why_delete_scmd"),
    ]

    operations = [
        migrations.AddField(
            model_name="measure",
            name="short_name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="measure",
            name="slug",
            field=models.SlugField(null=True, unique=True),
        ),
    ]
