# Generated by Django 5.1 on 2025-04-04 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("viewer", "0014_rename_route_whoroute_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vmp",
            name="who_routes",
            field=models.ManyToManyField(related_name="vmps", to="viewer.whoroute"),
        ),
    ]
