# Generated by Django 5.1.1 on 2024-11-01 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("viewer", "0015_precomputedmeasureaggregated_denominator_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year_month", models.DateField()),
                ("file_type", models.CharField(max_length=255)),
            ],
        ),
    ]
