# Generated by Django 5.1.1 on 2024-09-26 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("viewer", "0015_measure_short_name_measure_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrgSubmissionCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.DateField()),
                ("has_submitted", models.BooleanField()),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="viewer.organisation",
                    ),
                ),
            ],
            options={
                "unique_together": {("organisation", "month")},
            },
        ),
    ]
