# Generated by Django 5.1.1 on 2024-11-13 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("viewer", "0016_datastatus"),
    ]

    operations = [
        migrations.CreateModel(
            name="SCMDQuantity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year_month", models.DateField()),
                ("quantity", models.FloatField(null=True)),
                ("unit", models.CharField(max_length=50, null=True)),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scmd_quantities",
                        to="viewer.organisation",
                    ),
                ),
                (
                    "vmp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scmd_quantities",
                        to="viewer.vmp",
                    ),
                ),
            ],
            options={
                "ordering": ["year_month", "vmp__name", "organisation__ods_name"],
                "indexes": [
                    models.Index(fields=["vmp"], name="viewer_scmd_vmp_id_405301_idx"),
                    models.Index(
                        fields=["organisation"], name="viewer_scmd_organis_4e33e2_idx"
                    ),
                    models.Index(
                        fields=["year_month"], name="viewer_scmd_year_mo_2901a3_idx"
                    ),
                ],
            },
        ),
    ]
