# Generated by Django 5.1.1 on 2024-09-26 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("viewer", "0016_orgsubmissioncache"),
    ]

    operations = [
        migrations.AddField(
            model_name="orgsubmissioncache",
            name="successor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="successors",
                to="viewer.organisation",
            ),
        ),
    ]
