# Generated by Django 5.1 on 2025-04-14 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0017_indicativecost'),
    ]

    operations = [
        migrations.AddField(
            model_name='vmp',
            name='bnf_code',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
