# Generated by Django 5.1.1 on 2024-09-26 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("viewer", "0017_orgsubmissioncache_successor"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrecomputedMeasure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.DateField()),
                ("quantity", models.FloatField()),
                (
                    "measure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="precomputed_measures",
                        to="viewer.measure",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="precomputed_measures",
                        to="viewer.organisation",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["measure", "organisation", "month"],
                        name="viewer_prec_measure_81a373_idx",
                    )
                ],
                "unique_together": {("measure", "organisation", "month")},
            },
        ),
    ]
