# Generated by Django 5.1.1 on 2024-11-13 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("viewer", "0017_scmdquantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="measure",
            name="how_is_it_calculated",
            field=models.TextField(null=True),
        ),
    ]
