# Generated by Django 5.1.1 on 2024-09-26 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("viewer", "0018_precomputedmeasure"),
    ]

    operations = [
        migrations.AlterField(
            model_name="precomputedmeasure",
            name="quantity",
            field=models.FloatField(null=True),
        ),
    ]
