# Generated by Django 5.1 on 2025-04-28 15:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0018_vmp_bnf_code'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='atc',
            new_name='atc_code_idx',
            old_name='viewer_atc_code_918ea6_idx',
        ),
        migrations.RemoveField(
            model_name='atc',
            name='level',
        ),
        migrations.RemoveField(
            model_name='atc',
            name='parent',
        ),
        migrations.AddField(
            model_name='atc',
            name='level_1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='atc',
            name='level_2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='atc',
            name='level_3',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='atc',
            name='level_4',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='atc',
            name='level_5',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='atc',
            name='code',
            field=models.CharField(max_length=7, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid ATC code', regex='^[A-Z](?:[0-9]{2})?[A-Z]?[A-Z]?(?:[0-9]{2})?$')]),
        ),
    ]
