# Generated by Django 5.1.1 on 2024-11-13 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("viewer", "0018_measure_how_is_it_calculated"),
    ]

    operations = [
        migrations.AddField(
            model_name="measure",
            name="quantity_type",
            field=models.CharField(
                choices=[("dose", "Dose"), ("ingredient", "Ingredient Quantity")],
                default="dose",
                max_length=20,
            ),
        ),
    ]
