# Generated by Django 5.1 on 2025-05-07 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0019_rename_viewer_atc_code_918ea6_idx_atc_code_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='measure',
            name='first_published',
            field=models.DateField(null=True),
        ),
    ]
