# Generated by Django 5.1.1 on 2024-10-03 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("viewer", "0019_measure_quantity_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "code",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="DDD",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ddd", models.FloatField()),
                ("unit", models.CharField(max_length=50)),
                (
                    "atc_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ddds",
                        to="viewer.atc",
                    ),
                ),
                (
                    "route",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ddds",
                        to="viewer.route",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="vmp",
            name="routes",
            field=models.ManyToManyField(
                null=True, related_name="vmps", to="viewer.route"
            ),
        ),
    ]
