# Generated by Django 5.1 on 2025-06-07 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("viewer", "0020_measure_first_published"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemMaintenance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("enabled", models.BooleanField(default=False)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "System Maintenance",
                "verbose_name_plural": "System Maintenance",
            },
        ),
    ]
