# Generated by Django 5.1.1 on 2024-11-20 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("viewer", "0020_route_ddd_vmp_routes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="route",
            name="code",
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
