# Generated by Django 5.1.1 on 2024-11-21 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("viewer", "0021_alter_route_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="orgsubmissioncache",
            name="quantity_count",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="orgsubmissioncache",
            name="vmp_count",
            field=models.IntegerField(null=True),
        ),
    ]
