# Generated by Django 5.1 on 2025-06-18 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0021_systemmaintenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='vmp',
            name='df_ind',
            field=models.CharField(default='Not applicable', help_text='Dose form indicator', max_length=20),
        ),
        migrations.AddField(
            model_name='vmp',
            name='udfs',
            field=models.FloatField(help_text='Unit dose form size', null=True),
        ),
        migrations.AddField(
            model_name='vmp',
            name='udfs_uom',
            field=models.CharField(help_text='Unit dose form size unit of measure', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vmp',
            name='unit_dose_uom',
            field=models.CharField(help_text='Unit dose unit of measure', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='VMPIngredientStrength',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strnt_nmrtr_val', models.FloatField(help_text='Strength numerator value', null=True)),
                ('strnt_nmrtr_uom_name', models.CharField(help_text='Strength numerator unit of measure', max_length=100, null=True)),
                ('strnt_dnmtr_val', models.FloatField(help_text='Strength denominator value', null=True)),
                ('strnt_dnmtr_uom_name', models.CharField(help_text='Strength denominator unit of measure', max_length=100, null=True)),
                ('basis_of_strength_type', models.IntegerField(help_text='Type of basis of strength (1=Ingredient Substance, 2=Base Substance)', null=True)),
                ('basis_of_strength_name', models.CharField(help_text='Name of the basis of strength substance', max_length=255, null=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vmp_strengths', to='viewer.ingredient')),
                ('vmp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_strengths', to='viewer.vmp')),
            ],
            options={
                'indexes': [models.Index(fields=['vmp', 'ingredient'], name='viewer_vmpi_vmp_id_164e65_idx')],
                'unique_together': {('vmp', 'ingredient')},
            },
        ),
    ]
