# Generated by Django 5.1 on 2025-06-22 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0022_vmp_df_ind_vmp_udfs_vmp_udfs_uom_vmp_unit_dose_uom_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationLogic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logic_type', models.CharField(choices=[('dose', 'Dose'), ('ingredient', 'Ingredient Quantity'), ('ddd', 'DDD Quantity')], max_length=20)),
                ('logic', models.TextField()),
                ('ingredient', models.ForeignKey(blank=True, help_text='Required for ingredient quantity logic, null for dose/DDD logic', null=True, on_delete=django.db.models.deletion.CASCADE, to='viewer.ingredient')),
                ('vmp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculation_logic', to='viewer.vmp')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('logic_type__in', ['dose', 'ddd'])), fields=('vmp', 'logic_type'), name='unique_vmp_logic_type'), models.UniqueConstraint(condition=models.Q(('logic_type', 'ingredient')), fields=('vmp', 'ingredient', 'logic_type'), name='unique_vmp_ingredient_logic'), models.CheckConstraint(condition=models.Q(models.Q(('ingredient__isnull', False), ('logic_type', 'ingredient')), models.Q(('ingredient__isnull', True), ('logic_type__in', ['dose', 'ddd'])), _connector='OR'), name='ingredient_required_for_ingredient_logic')],
            },
        ),
    ]
