# Generated by Django 5.1.1 on 2024-12-07 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("viewer", "0022_orgsubmissioncache_quantity_count_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="organisation",
            index=models.Index(
                fields=["ods_code"], name="viewer_orga_ods_cod_8298ae_idx"
            ),
        ),
    ]
