# Generated by Django 5.1.1 on 2024-12-09 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("viewer", "0023_organisation_viewer_orga_ods_cod_8298ae_idx"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="measure",
            name="denominator_vmps",
        ),
        migrations.RemoveField(
            model_name="measure",
            name="numerator_vmps",
        ),
        migrations.CreateModel(
            name="MeasureVMP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("numerator", "Numerator"),
                            ("denominator", "Denominator"),
                        ],
                        max_length=20,
                    ),
                ),
                ("unit", models.CharField(max_length=50, null=True)),
                (
                    "measure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="measure_vmps",
                        to="viewer.measure",
                    ),
                ),
                (
                    "vmp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="measure_vmps",
                        to="viewer.vmp",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="measure",
            name="vmps",
            field=models.ManyToManyField(
                related_name="measures", through="viewer.MeasureVMP", to="viewer.vmp"
            ),
        ),
        migrations.AddIndex(
            model_name="measurevmp",
            index=models.Index(
                fields=["measure", "type"], name="viewer_meas_measure_8dabb8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="measurevmp",
            index=models.Index(fields=["vmp"], name="viewer_meas_vmp_id_e64177_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="measurevmp",
            unique_together={("measure", "vmp", "type")},
        ),
    ]
