# Generated by Django 5.2.3 on 2025-07-01 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0023_calculationlogic'),
    ]

    operations = [
        migrations.CreateModel(
            name='AWAREAntibiotic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Antibiotic name from AWARE list', max_length=255, unique=True)),
                ('aware_2019', models.CharField(help_text='AWARE classification for 2019', max_length=50, null=True)),
                ('aware_2024', models.CharField(help_text='AWARE classification for 2024', max_length=50, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='viewer_awar_name_b15d5f_idx')],
            },
        ),
        migrations.CreateModel(
            name='AWAREVMPMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aware_antibiotic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vmp_mappings', to='viewer.awareantibiotic')),
                ('vmp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aware_mappings', to='viewer.vmp')),
                ('vtm', models.ForeignKey(help_text='The VTM used to link antibiotic to VMP', on_delete=django.db.models.deletion.CASCADE, related_name='aware_mappings', to='viewer.vtm')),
            ],
            options={
                'indexes': [models.Index(fields=['aware_antibiotic', 'vmp'], name='viewer_awar_aware_a_5c102e_idx'), models.Index(fields=['vmp'], name='viewer_awar_vmp_id_81fe82_idx'), models.Index(fields=['vtm'], name='viewer_awar_vtm_id_e7880b_idx')],
                'unique_together': {('aware_antibiotic', 'vmp')},
            },
        ),
    ]
