# Generated by Django 5.2.3 on 2025-07-18 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0024_awareantibiotic_awarevmpmapping'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='calculationlogic',
            name='ingredient_required_for_ingredient_logic',
        ),
        migrations.AlterField(
            model_name='calculationlogic',
            name='ingredient',
            field=models.ForeignKey(blank=True, help_text='Required for ingredient quantity logic, null for dose/DDD logic or when no ingredients exist', null=True, on_delete=django.db.models.deletion.CASCADE, to='viewer.ingredient'),
        ),
    ]
