# Generated by Django 5.1.1 on 2024-12-10 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("viewer", "0024_remove_measure_denominator_vmps_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ddd",
            name="atc_code",
        ),
        migrations.RemoveField(
            model_name="vmp",
            name="atcs",
        ),
        migrations.RemoveField(
            model_name="ddd",
            name="route",
        ),
        migrations.DeleteModel(
            name="ATC",
        ),
        migrations.DeleteModel(
            name="DDD",
        ),
    ]
