# Generated by Django 5.1 on 2025-08-15 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "viewer",
            "0025_remove_calculationlogic_ingredient_required_for_ingredient_logic_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="measure",
            name="quantity_type",
            field=models.CharField(
                choices=[
                    ("scmd", "SCMD Quantity"),
                    ("dose", "Dose"),
                    ("ingredient", "Ingredient Quantity"),
                    ("ddd", "DDD"),
                    ("indicative_cost", "Indicative Cost"),
                ],
                default="dose",
                max_length=20,
            ),
        ),
    ]
