# Generated by Django 5.2.3 on 2025-08-18 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0026_alter_measure_quantity_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measure',
            name='draft',
        ),
        migrations.AddField(
            model_name='measure',
            name='status',
            field=models.CharField(choices=[('in_development', 'In Development'), ('preview', 'Preview'), ('published', 'Published')], default='in_development', max_length=20),
        ),
    ]
