# Generated by Django 5.2.6 on 2025-09-11 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0027_remove_measure_draft_measure_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasureAnnotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date when the annotation should appear')),
                ('label', models.CharField(help_text='Label to display on the annotation', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional description for the annotation', null=True)),
                ('colour', models.CharField(default='#DC3220', help_text='Colour of the annotation line (hex code)', max_length=7)),
                ('measure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='viewer.measure')),
            ],
            options={
                'ordering': ['date'],
                'indexes': [models.Index(fields=['measure', 'date'], name='viewer_meas_measure_e8cf23_idx')],
            },
        ),
    ]
