# Generated by Django 5.2.6 on 2025-09-16 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0028_measureannotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='measure',
            name='default_view_mode',
            field=models.CharField(choices=[('percentiles', 'NHS Trust'), ('icb', 'ICB'), ('region', 'Region'), ('national', 'National')], default='percentiles', help_text='Default view mode for this measure', max_length=20),
        ),
    ]
