# Generated by Django 5.2.6 on 2025-09-22 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0029_measure_default_view_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='AMP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('avail_restrict', models.CharField(help_text='Availability restriction description', max_length=255, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['code'], name='viewer_amp_code_9e3d27_idx')],
            },
        ),
        migrations.AddField(
            model_name='vmp',
            name='amps',
            field=models.ManyToManyField(related_name='vmps', to='viewer.amp'),
        ),
    ]
