# Generated by Django 5.2.6 on 2025-09-22 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0030_amp_vmp_amps'),
    ]

    operations = [
        migrations.AddField(
            model_name='vmp',
            name='special',
            field=models.BooleanField(default=False, help_text='Whether this VMP is a special (unlicensed medicine)'),
        ),
    ]
