# Generated by Django 5.2.6 on 2025-09-23 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0031_vmp_special'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrustType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Trust type name (e.g., ACUTE - TEACHING, COMMUNITY)', max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of the trust type', null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='viewer_trus_name_040408_idx')],
            },
        ),
        migrations.AddField(
            model_name='organisation',
            name='trust_type',
            field=models.ForeignKey(blank=True, help_text='Trust type from ERIC data', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organisations', to='viewer.trusttype'),
        ),
    ]
