# Generated by Django 5.2.11 on 2026-02-12 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0033_region_icb_organisation_changes'),
    ]

    operations = [
        migrations.AddField(
            model_name='measure',
            name='lower_is_better',
            field=models.BooleanField(blank=True, help_text='True if lower values indicate better practice; null for no value judgement', null=True),
        ),
    ]
