# Generated by Django 5.2.11 on 2026-02-27 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0034_rename_viewer_icb_code_idx_viewer_icb_code_3782ec_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancerAlliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Cancer Alliance code', max_length=20, unique=True)),
                ('name', models.CharField(help_text='Cancer Alliance name', max_length=255)),
            ],
        ),
        migrations.AddIndex(
            model_name='canceralliance',
            index=models.Index(fields=['code'], name='viewer_canc_code_23e4de_idx'),
        ),
        migrations.AddIndex(
            model_name='canceralliance',
            index=models.Index(fields=['name'], name='viewer_canc_name_97e704_idx'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='cancer_alliance',
            field=models.ForeignKey(blank=True, help_text='Cancer Alliance code', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organisations', to='viewer.canceralliance'),
        ),
    ]
