# Generated by Django 5.2.11 on 2026-03-06 09:48

import django.contrib.postgres.fields
from django.db import migrations, models


def clear_existing_quantity_data(apps, schema_editor):
    apps.get_model("viewer", "DDDQuantity").objects.all().delete()
    apps.get_model("viewer", "Dose").objects.all().delete()
    apps.get_model("viewer", "IndicativeCost").objects.all().delete()
    apps.get_model("viewer", "IngredientQuantity").objects.all().delete()
    apps.get_model("viewer", "SCMDQuantity").objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0035_canceralliance'),
    ]

    operations = [
        migrations.RunPython(
            clear_existing_quantity_data,
            migrations.RunPython.noop,
        ),
        migrations.CreateModel(
            name='IngredientQuantityUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='VMPQuantityUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_type', models.CharField(choices=[('scmd', 'SCMD'), ('dose', 'Dose')], max_length=20)),
                ('unit', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='dddquantity',
            name='data',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), help_text='Dense array [qty0, qty1, ...] aligned to DataStatus months (0 = no data)', null=True, size=None),
        ),
        migrations.AlterField(
            model_name='dose',
            name='data',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), help_text='Dense array [qty0, qty1, ...] aligned to DataStatus months (0 = no data)', null=True, size=None),
        ),
        migrations.AlterField(
            model_name='indicativecost',
            name='data',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), help_text='Dense array [qty0, qty1, ...] aligned to DataStatus months (0 = no data)', null=True, size=None),
        ),
        migrations.AlterField(
            model_name='ingredientquantity',
            name='data',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), help_text='Dense array [qty0, qty1, ...] aligned to DataStatus months (0 = no data)', null=True, size=None),
        ),
        migrations.AlterField(
            model_name='scmdquantity',
            name='data',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), help_text='Dense array [qty0, qty1, ...] aligned to DataStatus months (0 = no data)', null=True, size=None),
        ),
        migrations.AddField(
            model_name='ingredientquantityunit',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quantity_units', to='viewer.ingredient'),
        ),
        migrations.AddField(
            model_name='ingredientquantityunit',
            name='vmp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_quantity_units', to='viewer.vmp'),
        ),
        migrations.AddField(
            model_name='ingredientquantity',
            name='quantity_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingredient_quantities', to='viewer.ingredientquantityunit'),
        ),
        migrations.AddField(
            model_name='vmpquantityunit',
            name='vmp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quantity_units', to='viewer.vmp'),
        ),
        migrations.AddField(
            model_name='dose',
            name='quantity_unit',
            field=models.ForeignKey(limit_choices_to={'quantity_type': 'dose'}, on_delete=django.db.models.deletion.PROTECT, related_name='doses', to='viewer.vmpquantityunit'),
        ),
        migrations.AddField(
            model_name='scmdquantity',
            name='quantity_unit',
            field=models.ForeignKey(limit_choices_to={'quantity_type': 'scmd'}, on_delete=django.db.models.deletion.PROTECT, related_name='scmd_quantities', to='viewer.vmpquantityunit'),
        ),
        migrations.AddIndex(
            model_name='ingredientquantityunit',
            index=models.Index(fields=['ingredient', 'vmp'], name='viewer_ingr_ingredi_d79dce_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ingredientquantityunit',
            unique_together={('ingredient', 'vmp')},
        ),
        migrations.AddIndex(
            model_name='vmpquantityunit',
            index=models.Index(fields=['quantity_type', 'vmp'], name='viewer_vmpq_quantit_fa88bf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vmpquantityunit',
            unique_together={('quantity_type', 'vmp')},
        ),
    ]
