# Generated by Django 5.2.11 on 2026-03-19 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0036_add_unit_and_dense_data_to_quantity_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='measure',
            name='short_description',
            field=models.TextField(blank=True, help_text='Optional brief description for list view; falls back to description if absent', null=True),
        ),
    ]
