# Generated by Django 5.2.10 on 2026-03-10 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0037_measure_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='measure',
            name='archive_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='measure',
            name='archive_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='measure',
            name='status',
            field=models.CharField(choices=[('in_development', 'In Development'), ('preview', 'Preview'), ('published', 'Published'), ('archived', 'Archived')], default='in_development', max_length=20),
        ),
    ]
