# Generated by Django 5.2.11 on 2026-04-23 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0038_add_measure_archive_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='in_shelford_group',
            field=models.BooleanField(default=False, help_text='Whether this trust is in the Shelford Group (ODS codes from pipeline lookup table)'),
        )
    ]
