# Generated by Django 5.2.14 on 2026-06-05 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("viewer", "0039_add_shelford_group"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrustAdmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "organisation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trust_admissions",
                        to="viewer.organisation",
                    ),
                ),
                (
                    "period",
                    models.DateField(help_text="Start date of the activity month"),
                ),
                (
                    "count",
                    models.PositiveIntegerField(
                        help_text="Finished discharge episodes (elective + non-elective)"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="measure",
            name="denominator_type",
            field=models.CharField(
                blank=True,
                choices=[("1000_admissions", "Per 1000 admissions")],
                help_text="External denominator for rate measures",
                max_length=32,
                null=True,
            ),
        ),
        migrations.AddIndex(
            model_name="trustadmission",
            index=models.Index(
                fields=["organisation", "period"], name="viewer_trus_organis_1be228_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="trustadmission",
            unique_together={("organisation", "period")},
        ),
    ]
