# Generated by Django 5.2.14 on 2026-06-24 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("viewer", "0040_trustadmission_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="measure",
            name="y_axis_label",
            field=models.CharField(
                blank=True,
                help_text="Optional override for chart y-axis label; when unset, the label is derived from quantity type and products",
                max_length=255,
                null=True,
            ),
        ),
    ]
