# Generated by Django 5.2.14 on 2026-07-20 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0041_add_measure_y_axis_label'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='icb',
            new_name='viewer_icb_code_3782ec_idx',
            old_name='viewer_icb_code_idx',
        ),
        migrations.RenameIndex(
            model_name='icb',
            new_name='viewer_icb_name_421ef2_idx',
            old_name='viewer_icb_name_idx',
        ),
        migrations.RenameIndex(
            model_name='icb',
            new_name='viewer_icb_region__7a1098_idx',
            old_name='viewer_icb_region_idx',
        ),
        migrations.RenameIndex(
            model_name='region',
            new_name='viewer_regi_code_f5f940_idx',
            old_name='viewer_region_code_idx',
        ),
        migrations.RenameIndex(
            model_name='region',
            new_name='viewer_regi_name_e8ec22_idx',
            old_name='viewer_region_name_idx',
        ),
        migrations.AlterField(
            model_name='organisation',
            name='cancer_alliance',
            field=models.ForeignKey(blank=True, help_text='Cancer Alliance from ONS boundaries (postcode lookup)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organisations', to='viewer.canceralliance'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='icb',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organisations', to='viewer.icb'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organisations', to='viewer.region'),
        ),
    ]
