# Generated by Django 5.2.14 on 2026-10-08 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "viewer",
            "0042_rename_viewer_icb_code_idx_viewer_icb_code_3782ec_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="MeasureGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Text shown on the measure group page, under the group name.",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="measure",
            name="measure_group",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional group shared by similar measures. The measures list shows one card for the group.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="measures",
                to="viewer.measuregroup",
            ),
        ),
    ]
